version: "3"
services:
    web:
        # replace username/repo:tag with your name and image details
        image: website
        container_name: website
        ports:
            - "5000:80"
        volumes:
            - $PWD/website:/app
        networks:
            - custom_net
        command: python3 app.py
    mysql:
        image: mysql
        container_name: mymysql
        ports:
            - "3306:3306"
        volumes:
            - $PWD/mysql/conf/my.cnf:/etc/mysql/my.cnf
            - $PWD/mysql/data:/var/lib/mysql/douban_movie
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        #command: ls /var/lib/mysql/douban_movie
        networks:
            - custom_net
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - "$PWD/redis/data:/data"
        networks:
            - custom_net
networks:
    custom_net:
        external:
            name: app_net
